# Generated by Django 4.0.1 on 2022-01-24 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_alter_post_created_on_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caterory',
            field=models.ForeignKey(default='coding', max_length=60, on_delete=django.db.models.deletion.CASCADE, related_name='catego', to='blog.category'),
        ),
    ]
