# Generated by Django 4.0.1 on 2022-01-24 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_caterory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caterory',
            field=models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.CASCADE, related_name='catego', to='blog.category'),
        ),
    ]
