# Generated by Django 4.0.1 on 2022-01-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_caterory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='caterory',
        ),
    ]
