# Generated by Django 4.0.1 on 2022-01-24 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
